### ISSUE TITLE
give an option to choose beteween sql.Null* and pointers for NULL columns

### ISSUE THREAD

**Issue by fraenky8** [fraenky8/tables-to-go#14]
Implement one more command line flag to determine which data type to use for `NULL` columns:
- sql.Null* (current implementation)
- pointer to primitves

**Comment by kaihendry** [comment]
Could you also generate JSON tags with omitempty for optional NULL columns please?

**Comment by kaihendry** [comment]
Yeah, you're right. I can add them myself with :GoAddTags but I am super lazy with marking the optional values as omitempty.

**Comment by kaihendry** [comment]
I found the null documentation a little weird. https://youtu.be/1mnMmMF3Dx0?t=451

`native|primitive`? Just a comment. No need to change anything.

**Comment by fraenky8** [comment]
Hm I see, maybe I should point it more out which options means what.

- `sql` stands for the `sql.Null*` datatypes
- `primitive` and `native` map to the same thing namely using golang's builtin datatypes with pointers
