### ISSUE TITLE
MySQL 8 has UPPERCASE columns in information_schema

### ISSUE THREAD

**Issue by jinxmcg** [fraenky8/tables-to-go#25]
Hi, 

Mysql 8 has UPPERCASE columns in information_schema.tables and information_schema.columns therefore it will trigger errors:
``could not get tables: missing destination name TABLE_NAME in *[]*database.Table`` 
TABLE_NAME should be lowercase disregarding that in the query is lowercase ``select table_name ...``

However the fix is pretty easy by adding ``select table_name as 'table_name' from...`` in the queries in mysql.go like this:
`SELECT table_name as 'table_name'
		FROM information_schema.tables
		WHERE table_type = 'BASE TABLE'
		AND table_schema = ?
		ORDER BY table_name`
and
`SELECT
		  ordinal_position as 'ordinal_position',
		  column_name as 'column_name',
		  data_type as 'data_type',
		  column_default as 'column_default',
		  is_nullable as 'is_nullable',
		  character_maximum_length as 'character_maximum_length',
		  numeric_precision as 'numeric_precision',
		  column_key as 'column_key',
		  extra as 'extra'
		FROM information_schema.columns
		WHERE table_name = ?
		AND table_schema = ?
		ORDER BY ordinal_position`

Thank you

**Comment by fraenky8** [comment]
Hi @jinxmcg! Good catch thank you! Will open a PR to fix this ASAP 👍
