### ISSUE TITLE
How to generate struct with gureu/null?

### ISSUE THREAD

**Issue by bigBron** [fraenky8/tables-to-go#31]
Is there a plan to support the use of gureu/null?

**Comment by fraenky8** [comment]
No plans to add this. You can make a PR if needed - but tbh I dont see the need for this to be supported. It mixes JSON and SQL types and only is a wrapper around sql.Null* types as I can see from a quick scan of the code. You can already differentiate between `nil` ("null") and `sql.Null*` and zero values.

Also want to point to this section in the Readme: https://github.com/fraenky8/tables-to-go#where-are-the-json-tags
