### ISSUE TITLE
Where is the SQLite makefile?

### ISSUE THREAD

**Issue by Snazzyham** [fraenky8/tables-to-go#32]
Sorry if this has been answered before but I'm a little confused, I ran the `go get` command and it installed the binary into my $PATH, but I can't find the source or anything, so idk where to run the Makefile for SQLite3 from. 

Thanks.

**Comment by fraenky8** [comment]
Hi @Snazzyham - yes you are right, the instructions are misleading and implying that the `go get` command willl fetch everything. But it only fetches the repo inside your go modules cache and installs the binary. 

To get SQLite support you have to clone this repository and then run the Makefile inside it. Hope it answers your question?

**Comment by Snazzyham** [comment]
Ahh yes thank you so much that makes sense!
