### ISSUE TITLE
database/sql import not being set on models

### ISSUE THREAD

**Issue by rshingleton** [fraenky8/tables-to-go#33]
Generating models for a medium sized database and half the table models end up not getting decorated with database/sql. I can't see any reason in particular, most tables are simple. Some have a single import while others also import "time" or "github.com/go-sql-driver/mysql".

Using latest version installable by go get github.com/fraenky8/tables-to-go as of this morning, 9/21/2021.

Version: latest
Datbase: MariaDB - 10.2.9-MariaDB-log

Examples:

---

package database

import (
	"time"
)

type ActionAuditLog struct {
	Type    string         `db:"Type"`
	User    string         `db:"User"`
	Details  sql.NullString `db:"Details"`
	Time    time.Time      `db:"Time"`
}

---

package database

import (
	"github.com/go-sql-driver/mysql"
)

type MonitorSnapshot struct {
	SystemID string         `db:"SystemId"`
	Name     string         `db:"Name"`
	Time     mysql.NullTime `db:"Time"`
	Data      sql.NullString `db:"Data"`
}

---

package database

type SeriesData struct {
	SeriesID  int            `db:"SeriesId"`
	StartTime int            `db:"StartTime"`
	EndTime   int            `db:"EndTime"`
	Value      sql.NullString `db:"Value"`
	Weight    sql.NullString `db:"Weight"`
}

**Comment by fraenky8** [comment]
Closing this with the note, that fro now on `sql.NullTime` is used instead of the database driver specific null-time in https://github.com/fraenky8/tables-to-go/pull/38
