### ISSUE TITLE
support unix socket connection

### ISSUE THREAD

**Issue by bokunodev** [fraenky8/tables-to-go#34]
I always use unix socket and disable network in my local machine. it'd be great if this tool support to connect to mysql trough unix socket :slightly_smiling_face:

**Comment by fraenky8** [comment]
Hi @bokunodev - I created #37 to add a new `-socket` flag. Can you check if it works for you? I tested myself with MySQL and Postgres and both works:

MySQL:
```
tables-to-go -v -t mysql -u root -d database -socket /tmp/mysql.sock
```

Postgres:
```
tables-to-go -v -t pg -u postgres -d database -socket /tmp 
```
