### ISSUE TITLE
go:build comment without // +build comment

### ISSUE THREAD

**Issue by Tifinity** [fraenky8/tables-to-go#39]
I run go get,and it report this error:
internal/cli/tables-to-go-cli.go:12:2: //go:build comment without // +build comment

**Comment by fraenky8** [comment]
@Tifinity what's your go version?

**Comment by Tifinity** [comment]
go1.16.6 darwin/arm64
mac m1

**Comment by fraenky8** [comment]
Thats odd, there is no such build tags in this file but in [`pkg/database/sqlite_driver.go`.](https://github.com/fraenky8/tables-to-go/blob/master/pkg/database/sqlite_driver.go#L1-L0)

What I can say is, that this build constraint follows the new syntax as introduced in [Go v1.17](https://go.dev/doc/go1.17#build-lines). Also this tool requires [Go 1.17](https://github.com/fraenky8/tables-to-go/blob/master/go.mod#L3).

But good catch, I will update the Readme and use both, old and new build constraints as mentioned in the release notes.

**Comment by fraenky8** [comment]
@Tifinity I updated in #40 - can you try to run the following:

```
go install github.com/fraenky8/tables-to-go@master
```

**Comment by Tifinity** [comment]
1. Thanks, does need 1.17+ to install correctly
2. #40, use 1.16 is also ok

Thank you very much, your solution is in time

**Comment by fraenky8** [comment]
Awesome! Glad to hear it works! 👍
