### ISSUE TITLE
How to connect to Postgres/CockroachDB without SSL mode?!

### ISSUE THREAD

**Issue by aenawi** [fraenky8/tables-to-go#53]
Hi

I'm trying to connect to CockroachDB which uses the same connection DSN string as Postgres, but cannot find any arg parameter to disable the SSL mode! I'm receiving this error message:

```
pq: SSL is not enabled on the server
```

NB: I checked the source code, file "pkg/database/postgresql.go", function DSN(), line: 47. The sslmode already set to "disable" which means it should connect without SSL! Is this a bug?!

Any hints please?

**Comment by fraenky8** [comment]
This tool uses Go standard library for the DSN and Postgres driver. Can you try to create a minimal example of a go main program to connect to your CockroachDB using a working DSN and PG driver? My assumption is that the PG driver is not suitable for CockroachDB in the first place but I might be wrong.

I don't have experience with CockroachDB and also no time right now to look into this.

**Comment by aenawi** [comment]
Hi @fraenky8 

Thanks for the reply.

Actually it's compatible; since CockroachDB uses PostgreSQL wire protocol for the connection between clients and the server, so any driver or connector supports that protocol should work, I presume! Anyways, I did some research and I found that we need to change the DSN connection string for Postgres to URI connection string that start with `postgres://` to be able to connect to any DB that support PostgreSQL wire protocol, which in our case CockroachDB, and according to this [Stackoverflow post](https://stackoverflow.com/a/66514120), `pg` awaits  for this prefix.

The tests I made to connect to Postgres and CockroachDB (using Docker containers) and retrieve some tables to create the structs worked perfectly after making the required changes. However, since I'm working on my own project, I might face some issues, since some Postgres datatypes and/or features not fully supported by CockroachDB. I'll try to update you of any findings.

I've already made the required changes, and added a new `-sslmode` argument to make developers' life easier (I guess), and since CockroachDB conn. string is compatible with Postgres, I don't see any reason to create another new connector file. So I'll propose a PR.

Could you please have a look.

Thanks.

<br>

NB:
- Postgres version tested (15.3.0)
- CockroachDB version tested (22.2.8)

<br>

References:
1. https://stackoverflow.com/questions/66512318/unable-to-connect-to-postgresql-using-go-and-pq
2. https://www.cockroachlabs.com/docs/v23.1/connection-parameters#convert-a-url-for-different-drivers

**Comment by fraenky8** [comment]
Interesting! Thanks for your investigations! TIL 👍 

I will run some tests on my own this week but in meanwhile I will review the PR already, thanks, I think this new SSLMode param is really useful and shifts the control of this to the user of this tool. 👍

**Comment by fraenky8** [comment]
Fixed in #54
