### ISSUE TITLE
mysql type of database is still generating with pg types

### ISSUE THREAD

**Issue by kaihendry** [fraenky8/tables-to-go#6]
https://github.com/unee-t/tables-to-go/blob/bug1/tests/Persons.go#L14 is such an example

Please see:
* https://github.com/unee-t/tables-to-go/blob/bug1/tests/Makefile
* https://github.com/unee-t/tables-to-go/blob/bug1/tests/docker-compose.yml

This is how I `gen` the output.

**Comment by fraenky8** [comment]
@kaihendry thanks for reporting and good catch! Could reproduce the issue and fix it in https://github.com/fraenky8/tables-to-go/pull/11
